export enum UF {
    AC = <any>"Acre",
    AL = <any>"Alagoas",
    AP = <any>"Amapá",
    AM = <any>"Amazonas",
    BA = <any>"Bahia",
    CE = <any>"Ceará",
    DF = <any>"Distrito Federal",
    ES = <any>"Espírito Santo",
    GO = <any>"Goiás",
    MA = <any>"Maranhão",
    MT = <any>"Mato Grosso",
    MS = <any>"Mato Grosso do Sul",
    MG = <any>"Minas Gerais",
    PA = <any>"Pará",
    PB = <any>"Paraíba",
    PR = <any>"Paraná",
    PE = <any>"Pernambuco",
    PI = <any>"Piaui",
    RJ = <any>"Rio de Janeiro",
    RN = <any>"Rio Grande do Norte",
    RS = <any>"Rio Grande do Sul",
    RO = <any>"Rondônia",
    RR = <any>"Roraima",
    SC = <any>"Santa Catarina",
    SP = <any>"São Paulo",
    SE = <any>"Sergipe",
    TO = <any>"Tocantins"
}

export const UFs = [
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO"
];
